package:  access_control
version:  '2.3.3'
author:   Wolfgang Busch
supportpage: redaxo.org/support/community/

page:
    title: 'translate:access_control'
    perm:  admin[]
    icon:  rex-icon fa-hand-stop-o
    subpages:
        introduction: { title: 'translate:introduction' }
        description:  { title: 'translate:description' }
        details:      { title: 'translate:details' }

requires:
    redaxo: ^5.3.0
